using System;
using System.Collections.Generic;
using System.Text;

namespace User.FXProRpmSync
{
    /// <summary>
    /// SimPro's _STelemetryData (3136 bytes): what SimPro reads from the shared memory "/simgame" and converts for the
    /// wheel (TelemetryData_v2tov1). Offsets generated from simpro3.pdb V3.1.1 (FXProDashes/SimProLayout.cs, verified
    /// on the wheel). Kind: f = float, i = int32, s = UTF-16 string of Count chars.
    /// </summary>
    internal sealed class SimProTelemetry
    {
        public const int Size = 3136;

        public static readonly Dictionary<string, (int Off, char Kind, int Count)> Fields =
            new Dictionary<string, (int, char, int)>(StringComparer.OrdinalIgnoreCase)
        {
            {"engineTorque", (0, 'f', 1)},
            {"engineMap", (4, 'i', 1)},
            {"maxGears", (8, 'f', 1)},
            {"maxRpm", (12, 'f', 1)},
            {"maxFuel", (16, 'f', 1)},
            {"maxTurbo", (20, 'f', 1)},
            {"isDrsAvaiable", (24, 'i', 1)},
            {"isDrsEnabled", (28, 'i', 1)},
            {"isInPit", (32, 'i', 1)},
            {"isInPitLane", (36, 'i', 1)},
            {"turnIndicatorLeft", (40, 'i', 1)},
            {"turnIndicatorRight", (44, 'i', 1)},
            {"isTcActive", (48, 'i', 1)},
            {"isAbsActive", (52, 'i', 1)},
            {"isPitLimiterOn", (56, 'i', 1)},
            {"isAutoShifterOn", (60, 'i', 1)},
            {"isEngineRunning", (64, 'i', 1)},
            {"isEngineIgnitionOn", (68, 'i', 1)},
            {"isMapAllowed", (72, 'i', 1)},
            {"isGamePaused", (76, 'i', 1)},
            {"isGameRunning", (80, 'i', 1)},
            {"isAnyFrontWheelLocked", (84, 'i', 1)},
            {"isAnyRearWheelLocked", (88, 'i', 1)},
            {"isAnyWheelLocked", (92, 'i', 1)},
            {"rpm", (96, 'f', 1)},
            {"rpmLed", (100, 'i', 1)},
            {"rpmPercentage", (104, 'i', 1)},
            {"speed", (108, 'f', 1)},
            {"absLevel", (112, 'f', 1)},
            {"tcLevel", (116, 'f', 1)},
            {"tcCut", (120, 'f', 1)},
            {"drsLevel", (124, 'f', 1)},
            {"gear", (128, 'i', 1)},
            {"steerAngle", (132, 'f', 1)},
            {"brake", (136, 'f', 1)},
            {"clutch", (140, 'f', 1)},
            {"throttle", (144, 'f', 1)},
            {"handbrake", (148, 'f', 1)},
            {"gainLoss", (152, 'f', 1)},
            {"totalLaps", (156, 'i', 1)},
            {"completedLaps", (160, 'i', 1)},
            {"remainingLaps", (164, 'i', 1)},
            {"position", (168, 'i', 1)},
            {"currentLapTime", (172, 'i', 1)},
            {"lastLapTime", (176, 'i', 1)},
            {"bestLapTime", (180, 'i', 1)},
            {"allTimeBest", (184, 'i', 1)},
            {"sessionTimeRemain", (188, 'i', 1)},
            {"fuel", (192, 'f', 1)},
            {"fuelPercent", (196, 'f', 1)},
            {"turbo", (200, 'f', 1)},
            {"turboPercent", (204, 'f', 1)},
            {"blackFlag", (208, 'i', 1)},
            {"blueFlag", (212, 'i', 1)},
            {"checkeredFlag", (216, 'i', 1)},
            {"greenFlag", (220, 'i', 1)},
            {"orangeFlag", (224, 'i', 1)},
            {"whiteFlag", (228, 'i', 1)},
            {"yellowFlag", (232, 'i', 1)},
            {"redFlag", (236, 'i', 1)},
            {"brakeBias", (240, 'f', 1)},
            {"ersMax", (244, 'f', 1)},
            {"ersStored", (248, 'f', 1)},
            {"ersPercent", (252, 'i', 1)},
            {"ersMode", (256, 'i', 1)},
            {"pitch", (260, 'f', 1)},
            {"roll", (264, 'f', 1)},
            {"yaw", (268, 'f', 1)},
            {"sway", (272, 'f', 1)},
            {"surge", (276, 'f', 1)},
            {"heave", (280, 'f', 1)},
            {"tractionLoss", (284, 'f', 1)},
            {"wheelSlip0", (288, 'f', 1)},
            {"wheelSlip1", (292, 'f', 1)},
            {"wheelSlip2", (296, 'f', 1)},
            {"wheelSlip3", (300, 'f', 1)},
            {"suspensionPos0", (304, 'f', 1)},
            {"suspensionPos1", (308, 'f', 1)},
            {"suspensionPos2", (312, 'f', 1)},
            {"suspensionPos3", (316, 'f', 1)},
            {"suspensionSpeed0", (320, 'f', 1)},
            {"suspensionSpeed1", (324, 'f', 1)},
            {"suspensionSpeed2", (328, 'f', 1)},
            {"suspensionSpeed3", (332, 'f', 1)},
            {"carDamage0", (336, 'f', 1)},
            {"carDamage1", (340, 'f', 1)},
            {"carDamage2", (344, 'f', 1)},
            {"carDamage3", (348, 'f', 1)},
            {"carDamage4", (352, 'f', 1)},
            {"airTemperature", (356, 'f', 1)},
            {"waterTemperature", (360, 'f', 1)},
            {"brakeTemperature0", (364, 'f', 1)},
            {"brakeTemperature1", (368, 'f', 1)},
            {"brakeTemperature2", (372, 'f', 1)},
            {"brakeTemperature3", (376, 'f', 1)},
            {"tyreTemperature0", (380, 'f', 1)},
            {"tyreTemperature1", (384, 'f', 1)},
            {"tyreTemperature2", (388, 'f', 1)},
            {"tyreTemperature3", (392, 'f', 1)},
            {"tyreTemperatureInner0", (396, 'f', 1)},
            {"tyreTemperatureInner1", (400, 'f', 1)},
            {"tyreTemperatureInner2", (404, 'f', 1)},
            {"tyreTemperatureInner3", (408, 'f', 1)},
            {"tyreTemperatureMiddle0", (412, 'f', 1)},
            {"tyreTemperatureMiddle1", (416, 'f', 1)},
            {"tyreTemperatureMiddle2", (420, 'f', 1)},
            {"tyreTemperatureMiddle3", (424, 'f', 1)},
            {"tyreTemperatureOuter0", (428, 'f', 1)},
            {"tyreTemperatureOuter1", (432, 'f', 1)},
            {"tyreTemperatureOuter2", (436, 'f', 1)},
            {"tyreTemperatureOuter3", (440, 'f', 1)},
            {"tyreWear0", (444, 'f', 1)},
            {"tyreWear1", (448, 'f', 1)},
            {"tyreWear2", (452, 'f', 1)},
            {"tyreWear3", (456, 'f', 1)},
            {"tyreDirt0", (460, 'f', 1)},
            {"tyreDirt1", (464, 'f', 1)},
            {"tyreDirt2", (468, 'f', 1)},
            {"tyreDirt3", (472, 'f', 1)},
            {"tyrePressure0", (476, 'f', 1)},
            {"tyrePressure1", (480, 'f', 1)},
            {"tyrePressure2", (484, 'f', 1)},
            {"tyrePressure3", (488, 'f', 1)},
            {"oilPressure", (492, 'f', 1)},
            {"oilTemperature", (496, 'f', 1)},
            {"roadTemperature", (500, 'f', 1)},
            {"deltaToAllTimeBest", (504, 'f', 1)},
            {"deltaToSessionBest", (508, 'f', 1)},
            {"gapAhead", (512, 'i', 1)},
            {"gapBehind", (516, 'i', 1)},
            {"pushToPass", (520, 'i', 1)},
            {"frontAntiRollBar", (524, 'i', 1)},
            {"rearAntiRollBar", (528, 'i', 1)},
            {"diffAdjOnThrottle", (532, 'i', 1)},
            {"fuelPerLap", (536, 'i', 1)},
            {"throttleShape", (540, 'i', 1)},
            {"engineBraking", (544, 'i', 1)},
            {"diffEntry", (548, 'i', 1)},
            {"diffMiddle", (552, 'i', 1)},
            {"diffExit", (556, 'i', 1)},
            {"sessionType", (560, 'i', 1)},
            {"trackLength", (564, 'f', 1)},
            {"fuelCurrentLapConsumption", (568, 'f', 1)},
            {"fuelCurrentLapIsValidForTracking", (572, 'i', 1)},
            {"fuelLastLapConsumption", (576, 'f', 1)},
            {"fuelLitersPerLap", (580, 'f', 1)},
            {"fuelRemainingLaps", (584, 'f', 1)},
            {"fuelRemainingTime", (588, 'f', 1)},
            {"estimatedFuelRemaingLaps", (592, 'f', 1)},
            {"compactDelta", (596, 'f', 1)},
            {"dataUpdateFps", (600, 'f', 1)},
            {"dayNightMode", (604, 'i', 1)},
            {"defaultSoundInputIsMuted", (608, 'i', 1)},
            {"blinkingGear", (612, 'i', 1)},
            {"blinkingGearUP", (616, 'i', 1)},
            {"accelerationSway", (620, 'f', 1)},
            {"accelerationHeave", (624, 'f', 1)},
            {"accelerationSurge", (628, 'f', 1)},
            {"bestLapOpponentPosition", (632, 'i', 1)},
            {"bestLapOpponentSameClassPosition", (636, 'i', 1)},
            {"bestSplitDelta", (640, 'i', 1)},
            {"brakesTemperatureAvg", (644, 'f', 1)},
            {"brakesTemperatureMax", (648, 'f', 1)},
            {"brakesTemperatureMin", (652, 'f', 1)},
            {"carCoordinates01", (656, 'f', 1)},
            {"carCoordinates02", (660, 'f', 1)},
            {"carCoordinates03", (664, 'f', 1)},
            {"carDamagesAvg", (668, 'i', 1)},
            {"carDamagesMax", (672, 'i', 1)},
            {"carDamagesMin", (676, 'i', 1)},
            {"carId", (680, 's', 128)},
            {"CarSettings_currentDisplayedRPMPercent", (936, 'i', 1)},
            {"CarSettings_currentGearRedLineRPM", (940, 'i', 1)},
            {"CarSettings_FuelAlertActive", (944, 'i', 1)},
            {"CarSettings_FuelAlertEnabled", (948, 'i', 1)},
            {"CarSettings_FuelAlertLaps", (952, 'f', 1)},
            {"CarSettings_maxFUEL", (956, 'f', 1)},
            {"CarSettings_maxGears", (960, 'f', 1)},
            {"CarSettings_maxRPM", (964, 'f', 1)},
            {"CarSettings_RedLineRPM", (968, 'f', 1)},
            {"CarSettings_redLineDisplayedPercent", (972, 'i', 1)},
            {"CarSettings_RPMRedLinePerGearOverride", (976, 'i', 1)},
            {"CarSettings_RPMRedLineReached", (980, 'i', 1)},
            {"CarSettings_RPMRedLineSetting", (984, 'i', 1)},
            {"CarSettings_RPMShiftLight1", (988, 'i', 1)},
            {"CarSettings_RPMShiftLight2", (992, 'i', 1)},
            {"currentLap", (996, 'i', 1)},
            {"currentSectorIndex", (1000, 'i', 1)},
            {"engineStarted", (1004, 'i', 1)},
            {"flagName", (1008, 's', 32)},
            {"fuelUnit", (1072, 'i', 1)},
            {"globalAccelerationG", (1076, 'f', 1)},
            {"hasMultipleClassOpponents", (1080, 'i', 1)},
            {"instantConsumption_L100KM", (1084, 'f', 1)},
            {"instantConsumption_MPG_UK", (1088, 'f', 1)},
            {"instantConsumption_MPG_US", (1092, 'f', 1)},
            {"isInPitSince", (1096, 'i', 1)},
            {"isSessionRestart", (1100, 'i', 1)},
            {"lapInvalidated", (1104, 'i', 1)},
            {"lastLapTyreWearFrontLeft", (1108, 'f', 1)},
            {"lastLapTyreWearFrontRight", (1112, 'f', 1)},
            {"lastLapTyreWearRearLeft", (1116, 'f', 1)},
            {"lastLapTyreWearRearRight", (1120, 'f', 1)},
            {"lastPitStopDuration", (1124, 'i', 1)},
            {"lastSectorTime", (1128, 'i', 1)},
            {"maxEngineTorque", (1132, 'i', 1)},
            {"maxSpeedKmh", (1136, 'f', 1)},
            {"maxSpeedLocal", (1140, 'f', 1)},
            {"maxSpeedMph", (1144, 'f', 1)},
            {"oilPressureUnit", (1148, 'i', 1)},
            {"opponentsCount", (1152, 'i', 1)},
            {"orientationPitch", (1156, 'i', 1)},
            {"orientationPitchAcceleration", (1160, 'i', 1)},
            {"orientationRoll", (1164, 'i', 1)},
            {"orientationRollAcceleration", (1168, 'i', 1)},
            {"orientationYaw", (1172, 'i', 1)},
            {"orientationYawAcceleration", (1176, 'i', 1)},
            {"packetTime", (1180, 'i', 1)},
            {"playerClassOpponentsCount", (1184, 'i', 1)},
            {"playerLeaderboardPosition", (1188, 'i', 1)},
            {"playerName", (1192, 's', 32)},
            {"pushToPassActive", (1256, 'i', 1)},
            {"replayMode", (1260, 'i', 1)},
            {"sector1BestLapTime", (1264, 'i', 1)},
            {"sector1BestTime", (1268, 'i', 1)},
            {"sector1LastLapTime", (1272, 'i', 1)},
            {"sector1Time", (1276, 'i', 1)},
            {"sector2BestLapTime", (1280, 'i', 1)},
            {"sector2BestTime", (1284, 'i', 1)},
            {"sector2LastLapTime", (1288, 'i', 1)},
            {"sector2Time", (1292, 'i', 1)},
            {"sector3BestLapTime", (1296, 'i', 1)},
            {"sector3BestTime", (1300, 'i', 1)},
            {"sector3LastLapTime", (1304, 'i', 1)},
            {"sectorsCount", (1308, 'i', 1)},
            {"selfsplitDelta", (1312, 'i', 1)},
            {"sessionOdo", (1316, 'f', 1)},
            {"sessionOdoLocalUnit", (1320, 'f', 1)},
            {"sessionTimeLeft", (1324, 'i', 1)},
            {"sessionTypeName", (1328, 's', 32)},
            {"spectating", (1392, 'i', 1)},
            {"speedLocal", (1396, 'i', 1)},
            {"speedLocalUnit", (1400, 'i', 1)},
            {"speedMph", (1404, 'i', 1)},
            {"spotterCarLeft", (1408, 'i', 1)},
            {"spotterCarLeftAngle", (1412, 'i', 1)},
            {"spotterCarLeftDistance", (1416, 'i', 1)},
            {"spotterCarRight", (1420, 'i', 1)},
            {"spotterCarRightAngle", (1424, 'i', 1)},
            {"spotterCarRightDistance", (1428, 'i', 1)},
            {"stintOdo", (1432, 'f', 1)},
            {"stintOdoLocalUnit", (1436, 'f', 1)},
            {"TemperatureUnit", (1440, 'i', 1)},
            {"trackCode", (1444, 's', 32)},
            {"trackConfig", (1508, 's', 32)},
            {"trackId", (1572, 's', 128)},
            {"trackPositionMeters", (1828, 'f', 1)},
            {"trackPositionPercent", (1832, 'f', 1)},
            {"tyrePressureUnit", (1836, 'i', 1)},
            {"tyresDirtyLevelAvg", (1840, 'f', 1)},
            {"tyresDirtyLevelMax", (1844, 'f', 1)},
            {"tyresDirtyLevelMin", (1848, 'f', 1)},
            {"tyresTemperatureAvg", (1852, 'f', 1)},
            {"tyresTemperatureMax", (1856, 'f', 1)},
            {"tyresTemperatureMin", (1860, 'f', 1)},
            {"tyresWearAvg", (1864, 'f', 1)},
            {"tyresWearMax", (1868, 'f', 1)},
            {"tyresWearMin", (1872, 'f', 1)},
            {"gameNotificationActive", (1876, 'i', 1)},
            {"gameNotificationContent", (1880, 's', 128)},
            {"gameNotificationTitle", (2136, 's', 32)},
            {"gameVolume", (2200, 'i', 1)},
            {"heartRateMonitorLastBPM", (2204, 'i', 1)},
            {"heartRateMonitorSimulatedBloodPressure", (2208, 'i', 1)},
            {"loggingErrorsCount", (2212, 'i', 1)},
            {"loggingLastMessage", (2216, 's', 64)},
            {"loggingLastSeverity", (2344, 'i', 1)},
            {"cachedFormulasPerSecond", (2348, 'i', 1)},
            {"createdJSExpressions", (2352, 'i', 1)},
            {"createdNCALCExpressions", (2356, 'i', 1)},
            {"frameDuration", (2360, 'f', 1)},
            {"JSFormulasPerSecond", (2364, 'i', 1)},
            {"NALCFormulasPerSecond", (2368, 'f', 1)},
            {"NALCOptimizedFormulasPerSecond", (2372, 'f', 1)},
            {"recycledJSExpressions", (2376, 'i', 1)},
            {"recycledNCALCExpressions", (2380, 'i', 1)},
            {"pluginNotificationActive", (2384, 'i', 1)},
            {"pluginNotificationContent", (2388, 's', 64)},
            {"pluginNotificationPercentValue", (2516, 'f', 1)},
            {"pluginNotificationTitle", (2520, 's', 32)},
            {"systemVolume", (2584, 'i', 1)},
            {"carModelString", (2588, 's', 128)},
            {"trackNameString", (2844, 's', 128)},
            {"wheelAngularSpeed0", (3100, 'f', 1)},
            {"wheelAngularSpeed1", (3104, 'f', 1)},
            {"wheelAngularSpeed2", (3108, 'f', 1)},
            {"wheelAngularSpeed3", (3112, 'f', 1)},
            {"wheelSpeed0", (3116, 'f', 1)},
            {"wheelSpeed1", (3120, 'f', 1)},
            {"wheelSpeed2", (3124, 'f', 1)},
            {"wheelSpeed3", (3128, 'f', 1)},
            {"wheelSlipValue", (3132, 'f', 1)},
        };

        public readonly byte[] Buffer = new byte[Size];

        public void Clear() => Array.Clear(Buffer, 0, Buffer.Length);

        /// <summary>Writes a number to a float or int field (ints are rounded).</summary>
        public void Set(string name, double value)
        {
            var (off, kind, _) = Fields[name];
            if (double.IsNaN(value) || double.IsInfinity(value)) value = 0;
            if (kind == 'f') Write(off, BitConverter.GetBytes((float)value));
            else if (kind == 'i') Write(off, BitConverter.GetBytes((int)Math.Round(Math.Max(int.MinValue, Math.Min(int.MaxValue, value)))));
        }

        public void Set(string name, bool value) => Set(name, value ? 1 : 0);

        public void SetString(string name, string value)
        {
            var (off, kind, count) = Fields[name];
            if (kind != 's') return;
            Array.Clear(Buffer, off, count * 2);
            if (string.IsNullOrEmpty(value)) return;
            var bytes = Encoding.Unicode.GetBytes(value);
            Array.Copy(bytes, 0, Buffer, off, Math.Min(bytes.Length, (count - 1) * 2)); // keep a terminating 0
        }

        public double Get(string name)
        {
            var (off, kind, _) = Fields[name];
            return kind == 'f' ? BitConverter.ToSingle(Buffer, off) : kind == 'i' ? BitConverter.ToInt32(Buffer, off) : 0;
        }

        private void Write(int off, byte[] bytes) => Array.Copy(bytes, 0, Buffer, off, bytes.Length);
    }
}
